<?php
    $array1 = array("php" => "PHP", "java" => "JAVA","html" => "HTML", "CSS");
    $array2 = array( "PHP", "java" => "JAVA", "Zend");
    echo "<pre>";
    print_r($array1);
    echo "</pre>";
    echo "<pre>";
    print_r($array2);
    echo "</pre>";
    $diff = array_diff($array2, $array1);
    echo "<pre>";
    print_r($diff);
    echo "</pre>";
    $diff = array_diff_key($array1, $array2);
    echo "<pre>";
    print_r($diff);
    echo "</pre>";
    $diff = array_diff_assoc($array1, $array2);
    echo "<pre>";
    print_r($diff);
    echo "</pre>";
    $intersect = array_intersect($array1, $array2);
    echo "<pre>";
    print_r($intersect);
    echo "</pre>";
    $intersect = array_intersect_key($array1, $array2);
    echo "<pre>";
    print_r($intersect);
    echo "</pre>";
    $intersect = array_intersect_assoc($array1, $array2);
    echo "<pre>";
    print_r($intersect);
    echo "</pre>";
