<?php
    $array = array("PHP", "a", 1, 5, "HTML");
    $newArr = array_slice( $array, 1, 2);
    echo "<pre>";
    print_r($array);
    echo "</pre>";
    echo "<pre>";
    print_r($newArr);
    echo "</pre>";
    $array1 = array("PHP", "a", 1, 5, "HTML");
    $array2 = array("PHP", "a", 1, 5, "HTML");
    $newArr = array_slice( $array, 1, 2, true );
    echo "<pre>";
    print_r($newArr);
    echo "</pre>";
    $newArr = array_splice($array1, 2, 2, $array2);
    echo "<pre>";
    print_r($newArr);
    echo "</pre>";
    echo "<pre>";
    print_r($array1);
    echo "</pre>";
    $number = array(1, 24, 5, 7, 2, 5, 6);
    echo "<pre>";
    print_r($number);
    echo "</pre>";
    sort($number);
    echo "mảng sắp xếp  theo tăng dần theo giá trị";
    echo "<pre>";
    print_r($number);
    echo "</pre>";
    rsort($number);
    echo "mảng sắp xếp  theo giảm dần theo giá trị";
    echo "<pre>";
    print_r($number);
    echo "</pre>";
    $array = array("s" => "PHP", "a" => "CSS", "t" => "HTMLL", "h" => "Java");
    ksort($array);
    echo "mảng sắp xếp  theo tăng dần theo khóa";
    echo "<pre>";
    print_r($array);
    echo "</pre>";
    krsort($array);
    echo "mảng sắp xếp  theo giảm dần theo khóa";
    echo "<pre>";
    print_r($array);
    echo "</pre>";